import { signIn, signOut, useSession } from 'next-auth/react';

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { data: session } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Hello I am main</h1>
        <div>
          <button onClick={() => signIn()}>Sign In</button>
          <br />
          <button onClick={() => signOut()}>Sign Out</button>
        </div>
      </main>

      <footer>Hello I am footer</footer>
    </div>
  );
}
